// Code generated by generate.go. DO NOT EDIT.

package s1009

import (
	"testing"

	"github.com/amarpal/go-tools/analysis/lint/testutil"
)

func TestTestdata(t *testing.T) {
	testutil.Run(t, SCAnalyzer)
}
