// Code generated by generate.go. DO NOT EDIT.

package stylecheck

import (
	"github.com/amarpal/go-tools/analysis/lint"
	"github.com/amarpal/go-tools/stylecheck/st1000"
	"github.com/amarpal/go-tools/stylecheck/st1001"
	"github.com/amarpal/go-tools/stylecheck/st1003"
	"github.com/amarpal/go-tools/stylecheck/st1005"
	"github.com/amarpal/go-tools/stylecheck/st1006"
	"github.com/amarpal/go-tools/stylecheck/st1008"
	"github.com/amarpal/go-tools/stylecheck/st1011"
	"github.com/amarpal/go-tools/stylecheck/st1012"
	"github.com/amarpal/go-tools/stylecheck/st1013"
	"github.com/amarpal/go-tools/stylecheck/st1015"
	"github.com/amarpal/go-tools/stylecheck/st1016"
	"github.com/amarpal/go-tools/stylecheck/st1017"
	"github.com/amarpal/go-tools/stylecheck/st1018"
	"github.com/amarpal/go-tools/stylecheck/st1019"
	"github.com/amarpal/go-tools/stylecheck/st1020"
	"github.com/amarpal/go-tools/stylecheck/st1021"
	"github.com/amarpal/go-tools/stylecheck/st1022"
	"github.com/amarpal/go-tools/stylecheck/st1023"
)

var Analyzers = []*lint.Analyzer{
	st1000.SCAnalyzer,
	st1001.SCAnalyzer,
	st1003.SCAnalyzer,
	st1005.SCAnalyzer,
	st1006.SCAnalyzer,
	st1008.SCAnalyzer,
	st1011.SCAnalyzer,
	st1012.SCAnalyzer,
	st1013.SCAnalyzer,
	st1015.SCAnalyzer,
	st1016.SCAnalyzer,
	st1017.SCAnalyzer,
	st1018.SCAnalyzer,
	st1019.SCAnalyzer,
	st1020.SCAnalyzer,
	st1021.SCAnalyzer,
	st1022.SCAnalyzer,
	st1023.SCAnalyzer,
}
